// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-587zYTT4CjsSodIvEtnuNDiJ6jqxag',
    appId: '1:701222800972:android:185c3134b4af300432aee9',
    messagingSenderId: '701222800972',
    projectId: 'modeloangenda',
    storageBucket: 'modeloangenda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlkmcdCG1HTKB3c3fsXGC4AvPSIdZRr2o',
    appId: '1:701222800972:ios:e3921cf197c1d12c32aee9',
    messagingSenderId: '701222800972',
    projectId: 'modeloangenda',
    storageBucket: 'modeloangenda.appspot.com',
    iosClientId: '701222800972-gk9klq2ve4kbtivo1bai2umstl003cj9.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
}
